### ISSUE TITLE
null children causes crash

### ISSUE THREAD

**Issue by mrpatiwi** [Purii/react-native-tableview-simple#10]
```
null is not an object (evaluating 'child.props')
```

Perhaps filter `null` childs before rendering  `Section` childs on https://github.com/Purii/react-native-tableview-simple/blob/master/components/Section.js#L53-L77

**Comment by Purii** [comment]
@mrpatiwi Do you have an example?

**Comment by mrpatiwi** [comment]
I'm closing this issue, I fixed it upgrading React Native

**Comment by Purii** [comment]
@mrpatiwi Which version did you use before?

**Comment by miracle2k** [comment]
This is a real issue. It happens if you do for example this:

     <TableView><Section>
       {showFirstItem ? <Cell /> : null}
     </Section></TableView>

See also https://github.com/facebook/react/issues/4867

**Comment by Purii** [comment]
@miracle2k I do not get any errors with this:

```javascript
<Section>
   { false || null}
</Section>
```

What happens with your environment?

**Comment by miracle2k** [comment]
No error with this. But  ``{{ false && <View /> }}`` does trigger it. Might be some optimization going on there??
