### ISSUE TITLE
Don't validate children via propTypes

### ISSUE THREAD

**Issue by miracle2k** [Purii/react-native-tableview-simple#11]
I have something like this:

    <TableView>
          <Section header={_("Select card to pay with")}>
             {cards.map((card, idx) => {
                  return <Cell .... />
              })}

        <Cell title="Use a new card" ... />
      </Section>
    </TableView>

My console says:

     warning.js:45 Warning: Failed propType: Invalid prop `children` supplied to `Section`. Check the render method of `Foo`.

So the children, in my case, would be:

    [
        [Cell, Cell],
        Cell
    ]

Why are the propTypes for children defined? This seems very much overkill - and, maybe, hard to get right.

**Comment by Purii** [comment]
*Just open an issue, if your problem is still not fixed.*
