### ISSUE TITLE
PropTypes.oneOfType error in react-native 0.27.0 

### ISSUE THREAD

**Issue by CaveyChan** [Purii/react-native-tableview-simple#12]
![8_](https://cloud.githubusercontent.com/assets/16031190/15823953/8470716a-2c2f-11e6-8ae5-33937eda1a7b.jpg)

**Comment by Purii** [comment]
Are you using the most current version of `react-native-tableview-simple`?

**Comment by Purii** [comment]
_Just open an issue, if your problem is still not fixed._

**Comment by CaveyChan** [comment]
The problem is solved, thank you

**Comment by CaveyChan** [comment]
The problem is solved, thank you
