### ISSUE TITLE
Can you allow CustomCell to accept style as props

### ISSUE THREAD

**Issue by Abiola-MosesOlaniyan** [Purii/react-native-tableview-simple#13]
I am having problem styling customCell. default style is applied.

**Comment by Purii** [comment]
@Abiola-MosesOlaniyan Do you  have an example?

**Comment by Abiola-MosesOlaniyan** [comment]
Sorry I don't have example. When I use customCell everything is centered (because of the default style you apply). I want to have my custom applied ( there is no way to pass my style as props)

**Comment by Purii** [comment]
I will look for a solution to pass style as a prop.
In the meantime you could use `flex: 1` to expand your content to the full width.

**Comment by Purii** [comment]
Should be fixed with [v0.11.0](https://github.com/Purii/react-native-tableview-simple/commit/e1bf19bb15327701787556aa106d6f68a9c43733). :+1: 
*Just reopen the issue, if your problem is still not fixed.*
