### ISSUE TITLE
Custom styles for cell

### ISSUE THREAD

**Issue by PaulBGD** [Purii/react-native-tableview-simple#14]
Currently there's not very many ways to style a cell. Stuff like font size, padding, and others just don't exist. Recreating them with a CustomCell doesn't feel very good.

**Comment by Purii** [comment]
The `Cell` is written to imitate the native `Cell` of iOS. It's not that easy to allow full customization and keep the implementation of the accessories working without issues.
#### `Cell`:`contentContainerStyle`
A `Custom Cell` has the same initial "looking" as a `Cell` but supports the prop `contentContainerStyle`.  The only difference is, that you need to style the contents on your own.
Would that be a good alternative for you? I am always looking for other opinions. So maybe you could provide an example? Do you use accessories?

**Comment by PaulBGD** [comment]
Yeah I see what you mean. I guess it makes more sense to use a Custom Cell.
