### ISSUE TITLE
Add support for rightDetailColor?

### ISSUE THREAD

**Issue by joncursi** [Purii/react-native-tableview-simple#16]
I would like to style the right detail with a color.

<img width="365" alt="screen shot 2016-09-06 at 5 40 10 am" src="https://cloud.githubusercontent.com/assets/4974609/18269042/71e8a8ca-73f4-11e6-9b4b-16c1a6f5e119.png">

Right now I am achieving this via

```
                detail={
                  <Text
                    style={styles.legal}
                  >
                    Legal
                  </Text>
                }
```

However this results in a propTypes validation error on the detail prop: 

```
ExceptionsManager.js:78 Warning: Failed prop type: Invalid prop `detail` supplied to `Cell`
```

**Comment by Purii** [comment]
Sounds reasonable!
The prop `rightDetailColor` will be supported with the next release 👍
