### ISSUE TITLE
Missing separators after onPress toggling other cells

### ISSUE THREAD

**Issue by philo23** [Purii/react-native-tableview-simple#166]
First of all, this little library is great for putting together quick tableview layouts, so thanks for the great work! 👍 

Probably the easiest way to explain this bug is by seeing it in action, so here's a quick snack with two examples in it: https://snack.expo.io/@philo23/quiet-scone

Basically when you toggle the visibility of other cells inside a `<Section>`, the separators between the one you pressed on and the new cells seem to disappear. If the other cells are not pressable, the separator stays hidden. But if the other cells are pressable, the separator returns when you press on one of the other cells.

As far as I can tell, this affects both iOS and Android, but not the web version for some reason.

**Comment by Purii** [comment]
Hi @philo23!

Glad that you like it!

That's an interesting issue. Could be something with this rows: https://github.com/Purii/react-native-tableview-simple/blob/master/src/components/Section.tsx#L128-L140

It may take some time before I can take a closer look. If you find a solution in the meantime feel free to open a PR 👍

**Comment by philo23** [comment]
So I've done a little digging and it seems like `highlightedRowIndex` isn't getting reset back to undefined by `unhighlightRow` because the `onPressOut` callback isn't being fired from the <TouchableHighlight> used inside of the <Cell> component.

It's almost like <TouchableHighlight> is being unmounted or something before it gets a chance to call the onPressOut callback? but I'm not sure because that doesn't seem like it should work like that.

At first I thought it might be this line, https://github.com/Purii/react-native-tableview-simple/blob/f1964456cec653b542d909d516048fd3a5d6e9de/src/components/Section.tsx#L70 or line 66 because highlightedRowIndex could be set to index 0 or 1, but as far as I can tell it's not actually that. Though I'd be curious to find out why those checks are in there.

**Comment by Purii** [comment]
Yep. Just saw that.
Happened on my rewrite to TS... but that's not released yet.
So there must be another issue.

**Comment by philo23** [comment]
Just fixed my previous comment, looks like GitHub markdown was eating some of the `< />` tags... hopefully it should make a bit more sense now! Basically it seems like `<TouchableHighlight />` isn't firing off the onPressOut callback to un-highlight the row when you mess with the children of the `<Section>` presumably because somethings getting unmounted midpress? Not sure.

And I can definitely see the same issue on my iOS simulator, it's where I first noticed it. Let me try re-running that snack on my device though.

**Comment by Purii** [comment]
Seems to be some kind of race condition.
For me it works with the Snack and locally...

Looks like component doesn't get rerendered if the children change.
The `Touchable` triggers an update of `highlightedRowIndex ` which leads to a serenader of the `Section`. That's why it works after pressing the `Touchable` Component.

`Section:127-132` controls the rendering of the Separator. Could you try out to debug the conditions?

**Comment by philo23** [comment]
Great, I was just about to ask what the best way to try out the new TS version. I'll test out v3.0.0 now and let you know how it goes.

**Comment by philo23** [comment]
I've updated it and it appears to be working now in-simulator, but I think the actual issue might have been that my react-native dependency was actually out of date by a couple of minor versions 😅 

Weirdly the snack from earlier still seems to be broken even with the new v3 version... but I think this bug can probably be put down to something in React Native thats since been fixed!

**Comment by Purii** [comment]
Good to hear!

Feel free to close this issue if it works for you now 👍
