### ISSUE TITLE
DisclosureIndicator is different

### ISSUE THREAD

**Issue by AnOptimistSeePessimist** [Purii/react-native-tableview-simple#195]
![QQ20200524-123948](https://user-images.githubusercontent.com/27407218/82745973-f64ee700-9dbc-11ea-8e5b-10a5e53038c9.png)

![QQ20200524-124454](https://user-images.githubusercontent.com/27407218/82745974-f949d780-9dbc-11ea-92b9-d0fc7da49080.png)

### reproduce

https://snack.expo.io/@chengxiaodong1/react-native-tableview-simple

**Comment by Purii** [comment]
Hey @AnOptimistSeePessimist!

Should be fixed with `v3.2.0` via f455b8db703c67f5fb417e2410c7326e930374c1.

Can you verify that please, @AnOptimistSeePessimist?

**Comment by AnOptimistSeePessimist** [comment]
Yes that fixes it! Thanks for the quick response!
