### ISSUE TITLE
Alternate separators missing

### ISSUE THREAD

**Issue by chetstone** [Purii/react-native-tableview-simple#20]
I have this code:
```
          <Section style={{flex: 1}}
                   header="Sounds"
                   hideSeparator={false} > 
              { sounds.sounds.map((sound, index) => {
                return ((selectedIndex == index) ? 
                  <Cell  key={index} accessory="Checkmark" title={sound.name} onPress={(event) => this.onPress(index)}/> :
                  <Cell  key={index} title={sound.name} onPress={(event) => this.onPress(index)}/>);
               }) }
          </Section>
```
And only every other separator shows:

![simulator screen shot nov 12 2016 14 59 11](https://cloud.githubusercontent.com/assets/976343/20242371/dc9a5a1e-a8e8-11e6-9ea2-e74e3857d381.png)

What can I do about this? I've tried hiding the separators and adding bottom or top borders to each cell using styles and they don't show up at all.

**Comment by Purii** [comment]
I experienced this issue before. You won't get this on a real device.
Set the scale to 100% on the iOS Simulator and try it again. (*Simulator: Window > Scale > 100%*)

*Just open an issue, if your problem is still not fixed.*

**Comment by chetstone** [comment]
Ah yes, I've seen this before, I just forgot. Thanks so much for the reply.
