### ISSUE TITLE
insetLeft, insetRight issue on Separator component

### ISSUE THREAD

**Issue by hadnet** [Purii/react-native-tableview-simple#218]
I'm trying to use the Separator component and customize the insetLeft prop but remains a white straight line on the width insetLeft setting. I think it's some issue on the `backgroundColor` in Separator.tsx. Defining it to "transparent" solves my issue of constantly setting backgroundColor="transparent" though. This issue pop up because I'm using a dark theme.

```ts
const Separator: React.FC<SeparatorInterface> = ({
  backgroundColor = '#FFF',  // Here I'm using 'transparent'
  tintColor = '#C8C7CC',
  isHidden = false,
  insetLeft = 15,
  insetRight = 0,
  withSafeAreaView = Platform.OS === 'ios'
    ? parseInt(`${Platform.Version}`, 10) <= 10
      ? false
      : true
    : true,
}) => {
  const localStyles = {
    separator: [styles.separator, { backgroundColor: backgroundColor }],
    separatorInner: [
      styles.separatorInner,
      {
        backgroundColor: isHidden ? 'transparent' : tintColor,
        marginLeft: insetLeft,
        marginRight: insetRight,
      },
    ],
  };

  if (withSafeAreaView) {
    return (
      <SafeAreaView style={localStyles.separator}>
        <View style={localStyles.separatorInner} />
      </SafeAreaView>
    );
  }
  return (
    <View style={localStyles.separator}>
      <View style={localStyles.separatorInner} />
    </View>
  );
};

const styles = StyleSheet.create({
  separator: {},
  separatorInner: {
    height: StyleSheet.hairlineWidth,
  },
});
```

**Comment by Purii** [comment]
Hi @hadnet ! I'm going to look into that the next days. Shouldn't be an issue to update the default, but let me check.
- Support for Dark Theme is on the Roadmap 👍

**Comment by Purii** [comment]
Hi @hadnet! I just release `v.4.1.0` which supports dark mode out of the box.
Optionally you can add your own appearance through `customAppearances`.

Of course you should still be able to overwrite the prop `backgroundColor` of `Separator`.

Let me know if that solves your issue.
