### ISSUE TITLE
TableView style RN 0.39

### ISSUE THREAD

**Issue by Amurmurmur** [Purii/react-native-tableview-simple#23]
Please change tableview style from flex: 1 to flexGrow: 1.

Due to recent changes from RN 0.39 on android flex: 1 would give a bug and wont display a table at all.

here is the fixed tableview please include it with the new update of the component:

`
/* eslint-disable import/no-unresolved */
import React, {
  PropTypes,
} from 'react';

import {
  StyleSheet,
  View,
} from 'react-native';
/* eslint-enable import/no-unresolved */

const TableView = props => (
  <View style={styles.tableView}>
    {props.children}
  </View>
);

const styles = StyleSheet.create({
  tableView: {
    flexDirection: 'column',
    flexGrow:1,
  },
});

TableView.propTypes = {
  children: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.element),
    PropTypes.element,
  ]),
};

export default TableView;
`

**Comment by Purii** [comment]
Should be fixed with [v0.15.3](https://github.com/Purii/react-native-tableview-simple/commit/f781b6f9c406b26177b4ee4b4cfcefda4d45bf7d). :+1: 
_Just reopen the issue, if your problem is still not fixed._
