### ISSUE TITLE
Is there a property to change the Info Icon color?

### ISSUE THREAD

**Issue by esutton** [Purii/react-native-tableview-simple#25]
I would like to change the info icon to a colors used by my app's dark or light themes.

I would like to change form blue to my dark theme's green color.

I tried searching the repo but cannot find where the info icon comes from?  I searched for png and jpg.

Thanks in advance,

![screen shot 2016-12-14 at 12 43 56 pm](https://cloud.githubusercontent.com/assets/6115047/21195830/095edce8-c1fb-11e6-9dac-adb00eef5f9e.png)

**Comment by Purii** [comment]
That icon is build with CSS. You can use the prop `rightDetailColor`.
Have a look at the `example` project: [index.ios.js#L62](https://github.com/Purii/react-native-tableview-simple/blob/master/example/index.ios.js#L62).

```javascript
<Cell cellStyle="RightDetail" title="RightDetail" detail="Detail" rightDetailColor="#6cc644" />
```

**Comment by esutton** [comment]
**rightDetailColor** sets the detail text color but the icon remains blue color?

**Comment by Purii** [comment]
Sorry!

The right prop is `accessoryColor`.

```javascript
<Cell cellStyle="RightDetail" accessory="DetailDisclosure" title="RightDetail" detail="Detail" accessoryColor="#6cc644" />
```

**Comment by esutton** [comment]
My bad.  

Sorry I did not give accessoryColor a try!

Thank you for sharing your work.

Nice job!
