### ISSUE TITLE
Add `object` as an expected propType for title prop

### ISSUE THREAD

**Issue by joncursi** [Purii/react-native-tableview-simple#28]
The `title` prop should also accept values of type `object`. An example of this is a custom `<Text />` component that is used to format a value in some way, either pluralize it, translate it, or otherwise manipulate it. But the output of the render function is still a string. I.e.:

```jsx
<Cell
  ...
  title={
    <TextComponentThatTranslatesAndFormats
      text='Format me!'
    />
  }
  ...
```

The above emits the following warning to console:

Warning: Failed prop type: Invalid prop `title` supplied to `Cell`.

**Comment by Purii** [comment]
`node` would probably fit better?
This would allow something like:
```javascript
<Cell cellStyle="Basic" title={<Text style={{color: 'red'}}>SomeText</Text>} />
```

**Comment by Purii** [comment]
Should be on `npm` as `0.15.5` 👍 

*Just open an issue, if your problem is still not fixed.*

**Comment by joncursi** [comment]
💪 🙏
