### ISSUE TITLE
Text lacks selectable prop

### ISSUE THREAD

**Issue by drewvolz** [Purii/react-native-tableview-simple#30]
As of  react native v0.39, `<Text>` elements can be made selectable on iOS. `<Cell>` should allow for `selectable={true}` to be set within inner `<Text>` elements.

http://facebook.github.io/react-native/releases/0.39/docs/text.html#selectable

**Comment by Purii** [comment]
I'll look into it!

**Comment by Purii** [comment]
I'm thinking about a solution to support the selection of the whole cell but copy just the title.
Simply adding `selectable` to the title wouldn't help, since some `Cells` also have a detail-`Text`. Do you have an idea, @drewvolz?

**Comment by drewvolz** [comment]
I have not thought of a suitable way to implement this.

**Comment by Purii** [comment]
@drewvolz Have you already looked into [chirag04/react-native-tooltip](https://github.com/chirag04/react-native-tooltip) together with the [`Clipboard`-API](https://facebook.github.io/react-native/docs/clipboard.html)?

**Comment by drewvolz** [comment]
That’s a good solution. Thanks, @Purii.
