### ISSUE TITLE
Cell has default padding that can't be removed

### ISSUE THREAD

**Issue by manishtpatel** [Purii/react-native-tableview-simple#31]
Custom Cell defined with cellContentView gets default vertical padding, that can't be removed. For custom cells it should not preset any stylings or allow to override it.

cellContentView: {
    alignItems: 'center',
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'center',
    // independent from other cellViews
    paddingVertical: 10,
  },

**Comment by Purii** [comment]
Have you considered, replacing the contentView?

```javascript
  <Cell
    {...props}
    cellContentView={
      <View
        style={{ alignItems: 'center', flexDirection: 'row', flex: 1, paddingVertical: 10 }}
      >
        <Text
          allowFontScaling
          numberOfLines={1}
          style={{ flex: 1, fontSize: 20 }}
        >
          {props.title}
        </Text>
      </View>
    }
  />
```

See [Wrap `Cell`](https://github.com/Purii/react-native-tableview-simple#wrap-cell).

**Comment by Purii** [comment]
*Just open an issue, if your problem is still not fixed.*
