### ISSUE TITLE
How can i solve this by Using this Component

### ISSUE THREAD

**Issue by lavarajallu** [Purii/react-native-tableview-simple#37]
please click it once link  i have a issue.

[https://stackoverflow.com/questions/45841397/how-to-check-uncheck-individual-checkbox-in-react-native-table-component](url)

**Comment by Purii** [comment]
Are you using [`react-native-tableview`](https://github.com/aksonov/react-native-tableview) or `react-native-tableview-simple`?

**Comment by lavarajallu** [comment]
I am using react-native table view

**Comment by Purii** [comment]
So this is react-native-tableview-simple. Another component. Just follow that [link](https://github.com/aksonov/react-native-tableview).
