### ISSUE TITLE
Header and Footer Separators

### ISSUE THREAD

**Issue by liorzil** [Purii/react-native-tableview-simple#38]
Is there a way to get rid of the lines between the header/footer and the body of the tableview? My header and footer are transparent without text but a line still shows, separating them from the cells.

![image](https://user-images.githubusercontent.com/2922188/30071988-de942506-9236-11e7-9c56-235890d146fe.png)

**Comment by Purii** [comment]
Do you need the section component at all?

**Comment by liorzil** [comment]
No, I thought it was required in TableView. That solved it. Thanks.
