### ISSUE TITLE
Android - Header and Footer left margin

### ISSUE THREAD

**Issue by mrpatiwi** [Purii/react-native-tableview-simple#4]
On Android, section header and footer are missing left margin.

![image](https://cloud.githubusercontent.com/assets/7570744/12718675/ed2305c0-c8ce-11e5-8e1c-7db13c942e8f.png)

![image](https://cloud.githubusercontent.com/assets/7570744/12718696/00993dea-c8cf-11e5-92b6-4b199254ac37.png)

**Comment by Purii** [comment]
Should be fixed with [v0.6.0](https://www.npmjs.com/package/react-native-tableview-simple). :+1:
