### ISSUE TITLE
[iOS] Crash on ViewPropsTypes.style

### ISSUE THREAD

**Issue by esutton** [Purii/react-native-tableview-simple#41]
I had to remove ViewPropsTypes.style.

I was getting crashes when app started due to ViewPropsTypes.style after upgrading react-native-tableview-simple 0.16.4 -> 0.16.13

Xcode:
`2017-10-05 10:48:45.581 FieldScout[15242:54944] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: undefined is not an object (evaluating 'o.ViewPropTypes.style')', reason: 'Unhandled JS Exception: undefined is not an object (evaluating 'o.ViewPropT..., stack:
`

The following line depends on RN 0.44 or greater:

https://github.com/Purii/react-native-tableview-simple/blob/cf688dee9f421137f205f933e5424a95c2df764d/components/Cell.js#L430

`contentContainerStyle: ViewPropTypes.style,`

    "react": "~15.4.1",
    "react-native": "0.42.3",
    "react-native-tableview-simple": "^0.16.13",

Is there a way to make backwards compatible to < RN 0.44 ?

If not, should peerDependencies be updated?

```
  "peerDependencies": {
    "react": "*",
    "react-native": ">=0.44 || 0.50.0-rc"
  },
```

Thank you for sharing your work!

**Comment by Purii** [comment]
Thanks @esutton!

I would prefer to keep the usage of PropTypes consistent.
It would be great if you create a PR with updated peerDependencies 👍 

Hope that this is an option for your project.

**Comment by esutton** [comment]
If you want to require use of RN 0.44 or greater for your project, then I believe **ViewPropsTypes** is what you want to use.  I think the dependencies need to upgraded.

Unfortunately **ViewPropsTypes** breaks things for people like me who are using older the RN 0.44.
```
    "react": "~15.4.1",
    "react-native": "0.42.3",

```
I think I will fork your project and comment-out **ViewPropsTypes** until I am able to upgrade all my dependencies to >= RN 0.44

I do not know of a way to support both old (ViewProps) and new version (ViewPropsTypes) of RN
