### ISSUE TITLE
Bug in dark mode display

### ISSUE THREAD

**Issue by unmec** [Purii/react-native-tableview-simple#425]
Hello! When trying to implement dark mode, I found out that the package ignored the appearance param ```'dark'``` and always show light theme.

Then I found out the the if statement in ```TableView.tsx``` is the cause:
```
  if (
    (appearance === 'auto' && systemColorScheme === 'dark') ||
    systemColorScheme === 'light'
  ) 
```

Can be fixed with
```
  if (
    appearance === 'auto' &&
    (systemColorScheme === 'light' || systemColorScheme === 'dark')
  ) 
```

I don't know if this was the intended way, but if we are letting user to choose between automatic, light, and dark display, I believe the latter is the way to go.

Thanks!

**Comment by Purii** [comment]
Hi @unmec!

You're absolutely right.

Would be awesome if you create a PR with the fix.
Ideally also some "tests" (snapshots): https://github.com/Purii/react-native-tableview-simple/blob/master/src/components/__tests__/TableView.test.tsx

**Comment by Purii** [comment]
Hi @unmec!

Should be fixed in `v4.2.1`.

_Just reopen the issue, if it is still not fixed._

**Comment by unmec** [comment]
Hello @Purii , thanks for your great package.
I've been overwhelmed with db transfer to new server. I'll find some new opportunities to contribute the next time, promised! :-)
Thanks again.

**Comment by Purii** [comment]
No worries! Glad that you like the package :)
Hope everything went well 👍
