### ISSUE TITLE
If more than one column ? 

### ISSUE THREAD

**Issue by neel132** [Purii/react-native-tableview-simple#44]
Can I use this package, if I have more than 1 column?
-Thanks in advance

**Comment by Purii** [comment]
What do you mean by having more than 1 column?
In general the components are based on flexbox and are therefore flexible.

**Comment by neel132** [comment]
Thank-you you for your quick response, my precise question is ; how can I achieve the following structure: 
                  Col1       Col2       Col3
**Title**     Detail1 | Detail2 | Detail3 

In your stated example by using 
<Cell cellStyle="RightDetail" title="Title" detail="Detail1" />
we can achieve :
                  Col1
**Title**     Detail1

-Thanks

**Comment by Purii** [comment]
You can replace the contentView completely. Is this what you are looking for?
```javascript
<Cell
  cellContentView={
    <View
      style={{
        alignItems: "center",
        flexDirection: "row",
        flex: 1,
        paddingVertical: 10
      }}
    >
      <Text>Detail 1</Text>
      <Text>Detail 2</Text>
      <Text>Detail 3</Text>
    </View>
  }
/>
```

**Comment by neel132** [comment]
Thanks mate, its working like a charm :+1:
