### ISSUE TITLE
Section seems to add separator to elements that aren't <Cell>

### ISSUE THREAD

**Issue by hegelstad** [Purii/react-native-tableview-simple#47]
<img width="376" alt="screen shot 2018-04-05 at 13 19 04" src="https://user-images.githubusercontent.com/6997343/38363177-f49d95a0-38d3-11e8-9c4e-dc674f7c9105.png">

Look at the bottom <Cell> (Slutter), it has a separator at the bottom because i have a <DatePicker> (not wrapped in a cell) element underneath it that is hidden (shown when the cell is pressed).

Expected behavior: No separator on the bottom of the last cell even when there is a element beneath it. Then I would expect that I would have to add the separator manually if needed for my use case.

**Comment by Purii** [comment]
Is there a particular reason you hide the component, instead of rendering it only when needed? (https://reactjs.org/docs/conditional-rendering.html)
```
...
<Section>
 {renderCell && <Cell />}
</Section>
...

**Comment by hegelstad** [comment]
This is my code. I was unclear in my wording. I am conditionally hiding the DatePicker, but it seems like section is evaluating the code as being another cell, thereby adding a seperator to the bottom of the last cell which is seen in the picture.

```javascript
<ScrollView ref={list => this.list = list} style={{ backgroundColor: '#eff0f4', paddingBottom: 100 }}>
        <TableView>
          <Section>
            <Cell
              title="Hele dagen"
              cellAccessoryView={
                <Switch 
                  value={this.state.wholeday}
                  onValueChange={val => this.setState({wholeday: val, activeId: null})} />
              } />
            <Cell
              isDisabled={this.state.wholeday}
              title="Starter"
              cellAccessoryView={
                <Text style={{ color: (this.state.wholeday || this.state.firstTime) ? 'gray' : 'black' }}>
                  { this.state.firstTime
                    ? 'Velg tidspunkt...'
                    : moment(this.state.startTime).format('LT')
                  }
                </Text>
              }
              onPress={() => this.setState({activeId: 'start', firstTime: false})} />
            {this.state.activeId === 'start' &&
              <View>
                <DatePicker
                  style={{ backgroundColor: 'white' }}
                  mode="time"
                  date={this.state.startTime}
                  onDateChange={date => this.setState({ startTime: date })}
                />
              </View>
            }
            <Cell
              isDisabled={this.state.wholeday}
              title="Slutter"
              cellAccessoryView={
                <Text style={{ color: (this.state.wholeday || this.state.firstTime) ? 'gray' : 'black' }}>
                  { this.state.firstTime
                    ? 'Velg tidspunkt...'
                    : moment(this.state.endTime).format('LT')
                  }
                </Text>
              }
              onPress={() => {
                this.setState({ activeId: 'stop', firstTime: false})
                this.list.scrollToEnd({animated: true})
              }}/>
            {this.state.activeId === 'stop' &&
              <DatePicker
                style={{ backgroundColor: 'white' }}
                mode="time"
                date={this.state.endTime}
                onDateChange={date => this.setState({ endTime: date })}
              />
            }
          </Section>
          <Button
            disabled={this.state.firstTime && this.state.wholeday === false}
            title="Fullfør"
            onPress={() => this.props.handlePeriodSelection({
              startTime: this.state.startTime,
              endTime: this.state.endTime 
            })}/>
          <View style={{height: 30}} />
        </TableView>
      </ScrollView>
```

**Comment by Purii** [comment]
Ah. Got it!
Seems to be related to: https://github.com/facebook/react/issues/7685

Will look into it

**Comment by Purii** [comment]
Could you please check, if your issues are fixed with `v0.17.3`?

**Comment by hegelstad** [comment]
I did some digging. So as you can see from the code, i also have a `false` equation above the last `Cell`. This causes the index of the last `Cell` to be 3 instead of 2. Thus, not hiding the separator.

<img width="1336" alt="screen shot 2018-04-05 at 22 39 34" src="https://user-images.githubusercontent.com/6997343/38390683-4ea87ab2-3922-11e8-9886-31f7f3e480cc.png">

**Comment by Purii** [comment]
Ahh. So it's because you have an empty child between and not as the last one

**Comment by hegelstad** [comment]
That's correct, or they both start out as false.

They didn't render when i put them as the contentView in a cell, that's why they aren't cells.

**Comment by Purii** [comment]
Removed the usage of `React.Children.map`. Can you verify, that this fixed your issue?

**Comment by hegelstad** [comment]
Looks like the build haven't been pushed to npm yet? @Purii

**Comment by Purii** [comment]
Looks like you're right ;-)

**Comment by hegelstad** [comment]
Well, it works quite well now!

However, there is still one bug..

<img width="487" alt="screen shot 2018-04-06 at 10 15 05" src="https://user-images.githubusercontent.com/6997343/38409879-6d567660-3983-11e8-83d2-cad5b19599a0.png">


As you can see from my code/pictures, the cells have onPresses that conditionally shows the DatePicker beneath each cell respectively.

When i press the first cell (Starter), the first cell is rendered correctly with separators.
However, when I press the second cell (Slutter), there is no separator between the cell and the DatePicker (as it is when pressing the first cell) as seen in the picture above.

However, when pressing the second cell a second time while the DatePicker is open already, the separator is then added. I think this suggests some kind of timing error or failure to re-render?

For now I am just gonna add a separator manually above the bottom DatePicker.

Thanks for assisting me and for building this beauty!

**Comment by hegelstad** [comment]
I don't have my USB adapter handy so it would have to be another time. I'll try to let you know if I remember :)
