### ISSUE TITLE
Feature request: New input style

### ISSUE THREAD

**Issue by 10000multiplier** [Purii/react-native-tableview-simple#617]
How would we go about creating a cell with a TextInput on the right and a title on the left?

![image](https://user-images.githubusercontent.com/57633368/134263153-68f16798-4008-4c82-a2fd-22ad2c3b94dd.jpeg)

Thank you for building an awesome component.

**Comment by 10000multiplier** [comment]
Just realized it's already possible!

This code seems to do the trick:

```

<Cell
                                cellStyle="Basic"
                                title="Name"
                                cellAccessoryView={
                                    <TextInput
                                        style={{ fontSize: 16 }}
                                        placeholder="John Doe"
                                    />
                                }
                            />

```

**Comment by 10000multiplier** [comment]
![image](https://user-images.githubusercontent.com/57633368/134280990-773e935c-f11c-4351-9b1c-77fc228ab73a.jpeg)
Not working entirely as expected.

**Comment by Purii** [comment]
Hi @10000multiplier!
So this issue is solved?

**Comment by 10000multiplier** [comment]
> Hi @10000multiplier!
> So this issue is solved?

yes, you may close this!
