### ISSUE TITLE
implement testID

### ISSUE THREAD

**Issue by martin-badin** [Purii/react-native-tableview-simple#82]
Hello,

please, can you implement prop the testID to the table cell on the TouchableHighlight component?

**Comment by Purii** [comment]
The prop `testId` doesn't seem to be supported by `TouchableHighlight`: https://facebook.github.io/react-native/docs/0.59/touchablehighlight?

**Comment by Purii** [comment]
Hi @martin-badin !

With version 2.2.0 you should be able to set a testID for the Cell component. :-)

Just open an issue, if your problem is still not fixed.

**Comment by martin-badin** [comment]
👌thank you
