### ISSUE TITLE
Support Rounded Sections

### ISSUE THREAD

**Issue by SpencerLynn** [Purii/react-native-tableview-simple#84]
It would be great if sections and/or cells supported rounded corners.

Ideally it would be on the sections, but if that is too difficult, which it might be after peering though the code, (or if you disagree 😀) then having it on the Cell would be acceptable.

Something like this:
![image](https://user-images.githubusercontent.com/5921571/60858337-b42baf80-a1c2-11e9-9aca-6ed237ee5752.png)

I've struggled doing this with the props that exist today:

```
<Cell
    backgroundColor={'transparent'}
    contentContainerStyle={{
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        backgroundColor: 'white',
        borderColor: '
    }}
/>
```

results in

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/5921571/60858444-32885180-a1c3-11e9-9aaa-44ea6b4ecf31.png">

The border still seems off somewhere.

Let me know if I can help in any way!

**Comment by Purii** [comment]
Hi @SpencerLynn !

With version 2.3.0 I added some props to support rounded section corners. :-)

```js

<Section
 header="SUPPORT ROUNDED CORNERS"
 hideSurroundingSeparator
 roundedCorners
>
   <Cell cellStyle="Basic" title="Basic" />
</Section>
```

Just open an issue, if your problem is still not fixed.

**Comment by SpencerLynn** [comment]
Thanks for working on this! I'll check it out!

**Comment by SpencerLynn** [comment]
This worked great! Thanks for doing this @Purii !
