### ISSUE TITLE
Cell with Text Input Eats Touchable Press When Blurring

### ISSUE THREAD

**Issue by SpencerLynn** [Purii/react-native-tableview-simple#85]
In the following snack:

https://snack.expo.io/@slynn/react-native-tableview-simple---text-input-and-focus

When the text input is focused, you cannot click the touchable below until the text input is first blurred.

Steps:
1. Click into the text input to focus
2. Click on the "Pressable w/ accessory" cell.

Notice that you must first blur the text input.

Here is a snack that isolates the issue to show it doesn't seem to happen when not using react-native-tableview-simple.

https://snack.expo.io/@slynn/textinput-with-button

Let me know if you need anything else or if I am doing something wrong :)

**Comment by Purii** [comment]
@SpencerLynn Sorry for the really long delay.
It seems to be an issue with `ScrollView`:

```js
<ScrollView style={styles.stage}>
 <View style={{}}>
  <TextInput placeholder={'Test me'} />
  <Button onPress={() => alert('jop!')} title="Button" />
 </View>
</ScrollView>

// vs.

<View style={styles.stage}>
 <View style={{}}>
  <TextInput placeholder={'Test me'} />
  <Button onPress={() => alert('jop!')} title="Button" />
 </View>
</View>

// Working
<ScrollView style={styles.stage} keyboardShouldPersistTaps='handled'>
 <View style={{}}>
  <TextInput placeholder={'Test me'} />
  <Button onPress={() => alert('jop!')} title="Button" />
 </View>
</ScrollView>
```

Documentation > React Native > ScrollView: https://facebook.github.io/react-native/docs/scrollview#keyboardshouldpersisttaps
Default is `keyboardshouldpersisttaps:never`
> ..tapping outside of the focused text input when the keyboard is up dismisses the keyboard. When this happens, children won't receive the tap.

**Comment by SpencerLynn** [comment]
Thanks for finding that!
