### ISSUE TITLE
Dependencies is really 0.27.0-rc or this is a typo for 0.26.0-rc?

### ISSUE THREAD

**Issue by rturk** [Purii/react-native-tableview-simple#9]
Currently this is in package.json
 
  "peerDependencies": {
    "react-native": ">=0.25 || 0.27.0-rc"
  },

https://github.com/Purii/react-native-tableview-simple/blob/master/package.json#L21

**Comment by Purii** [comment]
Will be valid sometime next week.

Seems that I was even faster than the RN release cycle itself :-)
